name: cicd
run-name: ${{ github.actor }} is building with gradle
on:
  push:
    branches: [ "main","master" ]
  pull_request:
    branches:
      - "main"
      - "master"

permissions: read-all

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup jdk 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

  CD:
    needs: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: copy file via ssh password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "build/libs/*.jar"
          target: "source"
          rm: true

#      - name: Deploy
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.HOST }}
#          username: ${{ secrets.USERNAME }}
#          password: ${{ secrets.PASSWORD }}
#          port: ${{ secrets.PORT }}
#          script: |
#            SOURCE_DIR=source/build/libs
#            FILE_NAME=`find $SOURCE_DIR/*.jar -printf "%f\n"`
#            PID=`ps -ef | grep occupying | grep sudo | grep -v "bash -c" | awk '{print $2}'`
#
#            if [ -z "$PID" ]; then
#                    echo "#### THERE IS NO PROCESS ####"
#            else
#                    echo "#### KILL $PID ####"
#                    sudo kill $PID
#            fi
#
#            echo "#### RUN $SOURCE_DIR/$FILE_NAME ####"

#            sudo java -jar $SOURCE_DIR/$FILE_NAME > /dev/null 2>&1 &
